modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="instantbuidlings"
version="1.0.1"
displayName="InstantBuidlings"
credits="chivas477"
displayURL="https://mcreator.net"
authors="chivas477"

[[dependencies.instantbuidlings]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



