modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="instantbuidlings"
version="1.0.0"
displayName="InstantBuidlings"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="chivas477"

[[dependencies.instantbuidlings]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



